name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "Makefile"
  pull_request:
    paths:
      - "Dockerfile"
      - "Makefile"

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build docker images (dry)
        run: make image
        if: github.event_name != 'push'
      - name: Build docker images (push)
        run: make image-push
        if: github.event_name == 'push'
      - uses: homoluctus/slatify@v2.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "Build/image"
          icon_emoji: ship
          url: ${{ secrets.SLACK_WEBHOOK_KC_NOTIFY }}
