name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "Makefile"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - "Makefile"
      - ".github/workflows/build.yml"

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker images (dry)
        run: make image-release-dry
        if: github.event_name != 'push'
      - name: Build docker images (push)
        run: make image-release
        if: github.event_name == 'push'
      - uses: homoluctus/slatify@v2.0.0
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "Build/image"
          icon_emoji: ship
          url: ${{ secrets.SLACK_WEBHOOK_KC_NOTIFY }}
